nelmio_api_doc:
    documentation:
        info:
            title: Mon API Symfony
            description: Documentation de mon API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
