CREATE TABLE USERS(
   USER_D CHAR(64) ,
   Pseudo VARCHAR(24) ,
   SUBSCRIBERS INTEGER,
   JOIN_DATE DATE,
   UPLOADED_VIDEO INTEGER,
   IS_ADMIN BOOLEAN NOT NULL,
   PRIMARY KEY(USER_D)
);

CREATE TABLE Videos(
   ID_Video CHAR(256) ,
   LIKE_VID INTEGER NOT NULL,
   TITLE VARCHAR(128) ,
   VIDEO_DURATION INTEGER,
   VIDEO_URL VARCHAR(2048) ,
   THUMBNAIL_PATH VARCHAR(2048) ,
   UPLOAD_DATE TIMESTAMPZ,
   DISLIKE_VID INTEGER,
   DESCRIPTION VARCHAR(1024) ,
   Status BOOLEAN,
   USER_D CHAR(64)  NOT NULL,
   PRIMARY KEY(ID_Video),
   FOREIGN KEY(USER_D) REFERENCES USERS(USER_D)
);

CREATE TABLE Commentaries(
   COMMENTARY_ID CHAR(256) ,
   PINNED BOOLEAN,
   CREATOR_FAVOR BOOLEAN,
   COM_LIKE INTEGER,
   COM_DISLIKE INTEGER,
   CONTENU_COM VARCHAR(500) ,
   ID_Video CHAR(256)  NOT NULL,
   PRIMARY KEY(COMMENTARY_ID),
   FOREIGN KEY(ID_Video) REFERENCES Videos(ID_Video)
);
